# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.CharField(max_length=50, verbose_name='URL Slug')),
            ],
            options={
                'verbose_name_plural': 'species',
                'verbose_name': 'species',
            },
        ),
    ]
