# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 21:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='reports', verbose_name='Photo')),
            ],
            options={
                'verbose_name_plural': 'photos',
                'verbose_name': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('toggle', models.CharField(blank=True, choices=[('gps', 'Use GPS'), ('interactive', 'Point on Map'), ('manual', 'Enter Manually')], max_length=11, null=True, verbose_name='Location Mode')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='GPS Accuracy')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.Species', verbose_name='Species')),
            ],
            options={
                'verbose_name_plural': 'reports',
                'verbose_name': 'report',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='report.Report'),
        ),
    ]
